sudo: required
services:
  - docker

before_install:
  - docker build -t ofnanezn/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ofnanezn/react-test npm test -- --coverage

after_success:
  - docker build -t ofnanezn/multi-client ./client
  - docker build -t ofnanezn/multi-nginx ./multi-nginx
  - docker build -t ofnanezn/multi-server ./multi-server
  - docker build -t ofnanezn/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to docker-hub
  - docker push ofnanezn/multi-client
  - docker push ofnanezn/multi-nginx
  - docker push ofnanezn/multi-server
  - docker push ofnanezn/multi-worker